### PR TITLE
Allow higher TYPO3 versions

### PR DESCRIPTION
**Pull request by simonschaufi**
You don't want to release a new version each time a new TYPO3 major version is released

### CODE REVIEW

**Comment by sabbelasichon** [comment]
@simonschaufi Could you also add typo3-cms/core as a dependency in the composer.json.

**Comment by simonschaufi** [comment]
@koehlersimon ping

**Comment by koehlersimon** [comment]
"You don't want to release a new version each time a new TYPO3 major version is released" Why do you assume my Code will work in TYPO3 11.10.0 ? But yeah lets see. Version 4 of Slug will come anyways soon. Thanks

**Comment by simonschaufi** [comment]
If you you want to make a release for every new TYPO3 version then you also need to restrict the composer requirements.

**Pull request merged**
